name: Ticketify CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with environment variables (from GitHub Secrets)
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      run: |
        pytest -v